<script setup>
import { ref } from 'vue'
import axios from 'axios'

const showcase = ref(null)
const error = ref('')
const loading = ref(false)

const showcaseUrl =
  import.meta.env.VITE_BOOK_SHOWCASE_URL ||
  'https://fit5032-2026-lingdai-36667145.pages.dev/bookShowcase'

const loadShowcase = async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await axios.get(showcaseUrl)
    showcase.value = response.data
  } catch (caughtError) {
    showcase.value = null
    error.value = caughtError.response?.data?.error || caughtError.message
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <section class="page-section">
    <div class="container">
      <div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4">
        <div>
          <p class="section-eyebrow">Firestore cloud catalogue</p>
          <h1>Book Showcase</h1>
          <p class="section-intro mb-0">
            A visual catalogue generated by a custom cloud function from Firestore data.
          </p>
        </div>
        <button
          type="button"
          class="btn btn-primary align-self-md-end"
          :disabled="loading"
          @click="loadShowcase"
        >
          {{ loading ? 'Loading...' : 'Load Cloud Showcase' }}
        </button>
      </div>

      <div v-if="error" class="alert alert-danger" role="alert">{{ error }}</div>

      <div v-if="showcase">
        <div class="showcase-summary mb-4">
          <div>
            <p class="section-eyebrow mb-1">Live cloud response</p>
            <h2>{{ showcase.title }}</h2>
            <p class="mb-0 text-secondary">{{ showcase.message }}</p>
          </div>
          <div class="total-badge" aria-label="Number of books returned">
            <strong>{{ showcase.total }}</strong>
            <span>books</span>
          </div>
        </div>

        <div class="row g-3">
          <div v-for="(book, index) in showcase.books" :key="book.id" class="col-12 col-sm-6 col-lg-4">
            <article class="book-card h-100">
              <span class="book-number">{{ String(index + 1).padStart(2, '0') }}</span>
              <h3>{{ book.name }}</h3>
              <p class="mb-0 text-secondary">ISBN: {{ book.isbn }}</p>
            </article>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.showcase-summary {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 24px;
  padding: 24px;
  border-left: 5px solid #0f766e;
  background: #ecfdf3;
}

.total-badge {
  display: grid;
  flex: 0 0 92px;
  place-items: center;
  min-height: 76px;
  border: 1px solid #98a2b3;
  background: #ffffff;
}

.total-badge strong {
  font-size: 1.8rem;
  line-height: 1;
}

.total-badge span {
  color: #475467;
}

.book-card {
  position: relative;
  padding: 24px;
  border: 1px solid var(--mindbridge-line);
  border-radius: 8px;
  background: #ffffff;
}

.book-number {
  display: block;
  margin-bottom: 18px;
  color: #0f766e;
  font-weight: 800;
}

.book-card h3 {
  font-size: 1.1rem;
}

@media (max-width: 575px) {
  .showcase-summary {
    align-items: flex-start;
  }
}
</style>
